[package]
name = "naia-client"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
edition = "2018"

[dependencies]
naia-client-socket = { version = "0.1.0" }
naia-shared = { path = "../shared" }
cfg-if = "0.1.10"
log = "0.4"
byteorder = "1.3"