[package]
name = "gaia-derive"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[features]

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
quote = "1.0"
