[package]
name = "naia-server"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
edition = "2018"

[features]
use-udp = [ "naia-server-socket/use-udp" ]
use-webrtc = [ "naia-server-socket/use-webrtc" ]

[dependencies]
naia-server-socket = { path = "../naia-server-socket" } # { git = "https://github.com/connorcarpenter/naia-server-socket" } #
naia-shared = { path = "../naia-shared" } # { git = "https://github.com/connorcarpenter/naia-shared" } #
log = "0.4"
slotmap = { version = "0.4" }
byteorder = "1.3"
indexmap = "1.4.0"
ring = "0.16.15"