[package]
name = "naia-client"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
edition = "2018"

[dependencies]
naia-client-socket = { path = "../naia-client-socket" } # { git = "https://github.com/connorcarpenter/naia-client-socket" } #
naia-shared = { path = "../naia-shared" } # { git = "https://github.com/connorcarpenter/naia-shared" } #
cfg-if = "*"
log = "0.4"
byteorder = "1.3"