[package]
name = "gaia-shared"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
edition = "2018"

[dependencies]
gaia-socket-shared = { path = "../gaia-socket-shared" } # { git = "https://github.com/connorcarpenter/gaia-socket-shared" } #
byteorder = "1.3"
log = "0.4"
cfg-if = "*"
slotmap = { version = "0.4" }
indexmap = "1.4.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
# wasm-bindgen = { version = "0.2.45", features = [ ] }
js-sys = "0.3"