[package]
name = "naia-shared"
version = "0.1.2"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
description = "Common functionality shared between naia-server & naia-client crates"
documentation = "https://docs.rs/naia-shared"
homepage = "https://github.com/naia-rs/naia"
repository = "https://github.com/naia-rs/naia"
readme = "../README.md"
keywords = ["webrtc", "udp", "wasm", "networking", "gamedev"]
license = "MIT OR Apache-2.0"
categories = ["network-programming", "game-development", "wasm", "web-programming"]
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
naia-socket-shared = { version = "0.1.1" }
byteorder = "1.3"
log = "0.4"
cfg-if = "0.1.10"
nanoserde = "0.1.17"

[target.'cfg(target_arch = "wasm32")'.dependencies]
# wasm-bindgen = { version = "0.2.45", features = [ ] }
js-sys = "0.3"